---
- name: Test ping on localhost

  hosts: test
  user: user
  become: yes
#  vars:
#    - ssh_key : id_rsa.pub 
  tasks:
#    - name: add user 
#      include: adduser.yml


#    - name: remove user 
#      include: removeuser.yml


    - name: setup authorised key file in remote server  
      include: authorised-key.yml

    - name: add user 
      include: sudouser.yml

